### ISSUE TITLE
[BUG] [ANDROID] basic Page test coverage

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#4712]
## Basic Page test suite

(Check means all pass)

- [x] page-add-init-script.spec.ts
- [x] ok page-add-script-tag.spec.ts
- [x] ok page-add-style-tag.spec.ts
- [ ] page-basic.spec.ts
- [x] page-close.spec.ts
- [ ] page-emulate-media.spec.ts
- [x] page-evaluate-handle.spec.ts
- [x] page-evaluate.spec.ts
- [x] page-event-console.spec.ts
- [ ] page-event-crash.spec.ts
- [x] page-event-network.spec.ts
- [x] page-event-pageerror.spec.ts
- [x] page-event-popup.spec.ts
- [x] page-event-request.spec.ts
- [x] page-expose-function.spec.ts
- [x] page-fill.spec.ts
- [ ] page-goto.spec.ts
- [x] page-history.spec.ts
- [x] page-network-idle.spec.ts
- [x] page-route.spec.ts
- [ ] page-screenshot.spec.ts
- [x] page-select-option.spec.ts
- [x] page-set-content.spec.ts
- [x] page-set-extra-http-headers.spec.ts
- [x] page-set-input-files.spec.ts
- [x] page-wait-for-load-state.spec.ts
- [x] page-wait-for-navigation.spec.ts
- [x] page-wait-for-request.spec.ts
- [x] page-wait-for-response.spec.ts

## Extracted issues

- [x] (1) BrowserContext.newPage does not work (fixed in #4728)
- [x] (2) Page.check does not pass the actionability checks (fixed in #4755)
- [x] (3) The first example works the second not. The second uses Page.click which seems to act differently. (fixed in #4755)
- [ ] (4) (Storage.setCookies): Browser context management is not supported.Error

## Small reproducibles for the issues

(1):

```js
const { _android } = require('.');
(async () => {
  const [device] = await _android.devices();
  const context = await device.launchBrowser();
  for (const a of Array.from({length: 50})) {
    console.log("Creating a page")
    const page = await context.newPage()
    await page.goto('https://webkit.org/');
    await page.close()
    await new Promise((resolve) => setTimeout(resolve, 1000)
  }
  await device.close();
})();
```

(2)

```js
const { _android } = require('.');
(async () => {
  const [device] = await _android.devices();
  const context = await device.launchBrowser();
  const [page] = context.pages();
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.check('input'); // <- throws
  expect(await page.evaluate(() => window['checkbox'].checked)).toBe(true);
  await device.close();
})();
```

(3)

```js
const { _android } = require('.');
(async () => {
  const [device] = await _android.devices();
  const context = await device.launchBrowser();
  const [page] = context.pages();

  // both if condition's are official PW tests, if console.log() logs true all is good
  // the first case works but the second not, see the page.click which is probably the reason
  if (false) {
    await page.setContent('<a target=_blank rel=noopener href="/one-style.html">yo</a>');
    const [popup] = await Promise.all([
      page.waitForEvent('popup'),
      page.$eval('a', a => a.click()),
    ]);
    console.log(await page.evaluate(() => !!window.opener) === false)
    console.log(await popup.evaluate(() => !!window.opener) === false)
  } else {
    await page.setContent('<a target=_blank rel=noopener href="/one-style.html">yo</a>');
    const [popup] = await Promise.all([
      page.waitForEvent('popup'),
      // replacing that with the following works:
      // page.$eval('a', e => e.click()),
      page.click('a'),
    ]);
    console.log(await page.evaluate(() => !!window.opener) === false)
    console.log(await popup.evaluate(() => !!window.opener) === false)
  }

  await device.close();
})();
```

(4)
```
const { _android } = require('.');
(async () => {
  const [device] = await _android.devices();
  const context = await device.launchBrowser();
  const [page] = context.pages();
  await context.addCookies([{ url: "http://foobar.com", name: 'foo', value: 'bar'}]);
  await device.close();
})();
```

Used Chrome version, maybe we should use Chromium Canary? 
![image](https://user-images.githubusercontent.com/17984549/102259693-b8a7dc00-3f0f-11eb-99ef-375e55d2ce6b.png)

**Comment by mxschmitt** [comment]
Closed since we run the test now on the PR #4711
