### ISSUE TITLE
[Feature] Download cancellation support

### ISSUE THREAD

**Issue by starrify** [microsoft/playwright#6362]
Download cancellation may be considered useful in these sample scenarios:

- When the user doesn't expect a download to be initiated from the target URL / page at all.
- When the download takes too long.
- When the download has already transmitted / will transmit too much data.

The task may be roughly broken up into these steps:
- [x] Server side implement (Chromium): done in #6236.
- [ ] Server side implement (Firefox): to-do.
- [ ] Server side implement (WebKit): to-do.
- [x] Client side implement: done in #6236.
- [x] Documentation: done in #6236 (only for the existing Chromium implement)
- [x] Unit test: done in #6236 (only for the existing Chromium implement)

**Comment by mxschmitt** [comment]
This was implemented in https://github.com/microsoft/playwright/issues/7283. Thanks for the chromium contribution!
